"""
Artifact Service

This service is responsible for storing and retrieving artifacts.
Artifacts are intermediate data products generated by agents.
"""

from typing import Dict, Optional
from dataclasses import dataclass, field
from datetime import datetime
import json


@dataclass
class Artifact:
    """Represents an artifact generated by an agent"""
    name: str
    content: bytes
    mime_type: str
    created_at: datetime = field(default_factory=datetime.now)
    metadata: Dict = field(default_factory=dict)


class InMemoryArtifactService:
    """
    In-memory artifact storage service.
    For production use, this should be replaced with persistent storage.
    """
    
    def __init__(self):
        self._artifacts: Dict[str, Artifact] = {}
    
    async def create(self, name: str, content: bytes, mime_type: str, 
                    metadata: Optional[Dict] = None) -> Artifact:
        """
        Create and store a new artifact
        
        Args:
            name: Unique identifier for the artifact
            content: The artifact content as bytes
            mime_type: MIME type of the content
            metadata: Optional metadata dictionary
        
        Returns:
            The created Artifact object
        """
        artifact = Artifact(
            name=name,
            content=content,
            mime_type=mime_type,
            metadata=metadata or {}
        )
        self._artifacts[name] = artifact
        return artifact
    
    async def get(self, name: str) -> Optional[Artifact]:
        """
        Retrieve an artifact by name
        
        Args:
            name: The artifact name
        
        Returns:
            The Artifact object or None if not found
        """
        return self._artifacts.get(name)
    
    async def delete(self, name: str) -> bool:
        """
        Delete an artifact
        
        Args:
            name: The artifact name
        
        Returns:
            True if deleted, False if not found
        """
        if name in self._artifacts:
            del self._artifacts[name]
            return True
        return False
    
    async def list(self) -> list[Artifact]:
        """
        List all artifacts
        
        Returns:
            List of all stored artifacts
        """
        return list(self._artifacts.values())
    
    def clear(self):
        """Clear all artifacts (useful for testing)"""
        self._artifacts.clear()


# Global artifact service instance
artifact_service = InMemoryArtifactService()