// @ts-nocheck

/**
 * Test Agent
 * 
 * This agent is responsible for validating the data fetched from the Snapchat API
 * and the insights generated by the analysis agent.
 */

import { Agent } from "@google/generative-ai-agents";

export class TestAgent extends Agent {
  async run(snapchatData: any, insights: string) {
    console.log("Test Agent: Validating data");

    // 1. Validate Snapchat data
    if (!snapchatData || !snapchatData.totalFollowers) {
      throw new Error("Invalid Snapchat data: missing totalFollowers");
    }

    // 2. Validate insights
    if (!insights || typeof insights !== "string") {
      throw new Error("Invalid insights: not a string");
    }

    console.log("Test Agent: Data validation complete");

    return true;
  }
}
