"""
Test Agent

This agent is responsible for validating the data fetched from the Snapchat API
and the insights generated by the analysis agent.
"""

import sys
import os
from typing import Dict, Any

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.base_agent import Agent


class TestAgent(Agent):
    """
    Agent responsible for validating data integrity and format.
    
    This agent:
    1. Validates Snapchat data structure
    2. Validates insights format
    """
    
    async def run(self, snapchat_data: Dict[str, Any], insights: str) -> bool:
        """
        Validate Snapchat data and insights
        
        Args:
            snapchat_data: Dictionary containing Snapchat analytics data
            insights: Generated insight text
        
        Returns:
            True if validation passes
        
        Raises:
            ValueError: If validation fails
        """
        print("Test Agent: Validating data")
        
        # 1. Validate Snapchat data
        if not snapchat_data or "totalFollowers" not in snapchat_data:
            raise ValueError("Invalid Snapchat data: missing totalFollowers")
        
        # 2. Validate insights
        if not insights or not isinstance(insights, str):
            raise ValueError("Invalid insights: not a string")
        
        if len(insights.strip()) == 0:
            raise ValueError("Invalid insights: empty string")
        
        print("Test Agent: Data validation complete")
        
        return True